### ISSUE TITLE
Phase.VALIDATION

### ISSUE THREAD

**Issue by flipside17** [Zhhuizhe/AGAEMD#1]
你好，请问分别运行Phase.VALIDATION和Phase.TEST得到的结果有什么不同吗

**Comment by Zhhuizhe** [comment]
你好，Phase.VALIDATION输出的是5折交叉验证的均值结果，该过程不涉及测试集，仅用于调整模型参数；Phase.TEST输出的是测试集上预测结果。在较优的参数设置下，两者的预测结果可能会有些区别，但整体的差异应该不会特别大。
